Repository hmcts/finrem-notification-service, pull requests merged in 2019-12, with the labels that each got.

#84 Removing the cause of break for pipeline in FR-COS
  Jenkinsfile_CNP
Labels: ns:finrem-ns-pr-84

#85 updating terraform and jenkins to fix demo environment
  Jenkinsfile_CNP
  infrastructure/main.tf
Labels: ns:finrem-ns-pr-85

#87 Fix terraform script
  infrastructure/main.tf
Labels: ns:finrem-ns-pr-87

#89 Making string a boolean
  infrastructure/main.tf
Labels: ns:finrem-ns-pr-89

#90 Terraform syntax fix
  infrastructure/main.tf
Labels: ns:finrem-ns-pr-90
