Repository hmcts/finrem-notification-service, pull requests merged in 2020-04, with the labels that each got.

#118 Adding reforms logging dependencies
  build.gradle
Labels: ns:financial-remedy, rel:finrem-ns-pr-118

#119 Hotfix infra
  build.gradle
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:financial-remedy, rel:finrem-ns-pr-119

#123 sending contested application issued email
  build.gradle
  src/main/java/uk/gov/hmcts/reform/finrem/notifications/controllers/NotificationController.java
  src/main/java/uk/gov/hmcts/reform/finrem/notifications/domain/EmailTemplateNames.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/controllers/NotificationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/integrationtest/NotifyContestedApplicationIssuedTest.java
  src/test/resources/application.properties
  src/test/resources/fixtures/contestedApplicationIssued.json
Labels: ns:financial-remedy, rel:finrem-ns-pr-123
