Repository hmcts/finrem-notification-service, pull requests merged in 2020-10, with the labels that each got.

#182 suppress zap dependency check error
  audit.json
  build.gradle
  src/main/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-182

#183 upgrade to terraform 13
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-183

#176 FR-1813: send general order email
  dependency-check-suppressions.xml
  src/main/java/uk/gov/hmcts/reform/finrem/notifications/controllers/ConsentedNotificationController.java
  src/main/java/uk/gov/hmcts/reform/finrem/notifications/controllers/ContestedNotificationController.java
  src/main/java/uk/gov/hmcts/reform/finrem/notifications/domain/EmailTemplateNames.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/controllers/ConsentedNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/controllers/ContestedNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/domain/EmailTemplateNamesTest.java
  src/test/resources/application.properties
  src/test/resources/fixtures/consentedGeneralOrder.json
  src/test/resources/fixtures/contestedGeneralOrder.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-176

#185 Fix nightly test failures
  audit.json
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-185
