Repository hmcts/finrem-notification-service, pull requests merged in 2020-07, with the labels that each got.

#153 Bumped to Java 11
  .travis.yml
  Dockerfile
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-153

#155 ignore cookie errors
  audit.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-155

#156 Fix nightly build
  audit.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-156

#154 Implementing contested order not approved notification
  src/main/java/uk/gov/hmcts/reform/finrem/notifications/controllers/ContestedNotificationController.java
  src/main/java/uk/gov/hmcts/reform/finrem/notifications/domain/EmailTemplateNames.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/controllers/ContestedNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/domain/EmailTemplateNamesTest.java
  src/test/resources/application.properties
  src/test/resources/fixtures/contestOrderNotApproved.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-154

#157 FR-1572 & FR-1578: Add endpoints for contested consent order approved and not approved
  src/main/java/uk/gov/hmcts/reform/finrem/notifications/controllers/ContestedNotificationController.java
  src/main/java/uk/gov/hmcts/reform/finrem/notifications/domain/EmailTemplateNames.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/controllers/ContestedNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/domain/EmailTemplateNamesTest.java
  src/test/resources/application.properties
  src/test/resources/fixtures/contestedConsentOrderApproved.json
  src/test/resources/fixtures/contestedConsentOrderNotApproved.json
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-157
