Repository hmcts/finrem-notification-service, pull requests merged in 2021-01, with the labels that each got.

#202 fix dependency check fail
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-202

#205 Bumping versions and removing vulns/suppressions
  build.gradle
  dependency-check-suppressions.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-205

#206 security scan update for nightly
  security.sh
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-206

#207 FR-1929: add email notification for consented order not approved sent
  dependency-check-suppressions.xml
  src/main/java/uk/gov/hmcts/reform/finrem/notifications/controllers/ConsentedNotificationController.java
  src/main/java/uk/gov/hmcts/reform/finrem/notifications/domain/EmailTemplateNames.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/controllers/BaseNotificationTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/controllers/ConsentedNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/controllers/ContestedNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/domain/EmailTemplateNamesTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/service/EmailServiceTest.java
  src/test/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-207
