Repository hmcts/finrem-notification-service, pull requests merged in 2022-04, with the labels that each got.

#271 DFR-975: resolve spring dependency
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-271

#270 DFR-879: [FR 2022] - Maintenance Pending Suit - New Event - List for …
  src/main/java/uk/gov/hmcts/reform/finrem/notifications/controllers/ContestedNotificationController.java
  src/main/java/uk/gov/hmcts/reform/finrem/notifications/domain/EmailTemplateNames.java
  src/main/resources/application.properties
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/controllers/ContestedNotificationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/domain/EmailTemplateNamesTest.java
  src/test/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-270

#276 Suppressing spring-core
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-276
