Repository hmcts/finrem-notification-service, pull requests merged in 2022-08, with the labels that each got.

#295 DFR-1086 Update Readme
  README.md
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-295

#293 DFR-1126: variation order
  src/main/java/uk/gov/hmcts/reform/finrem/notifications/domain/NotificationRequest.java
  src/main/java/uk/gov/hmcts/reform/finrem/notifications/service/EmailService.java
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/domain/NotificationRequestTest.java
  src/test/java/uk/gov/hmcts/reform/finrem/notifications/service/EmailServiceTest.java
  src/test/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-293

#296 Add backstage configuration file
  catalog-info.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-296
