Repository hmcts/finrem-notification-service, pull requests merged in 2023-02, with the labels that each got.

#322 fix owasp dependency
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-322

#324 dependency fix patch
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-324

#325 Fixed nightly-vulnerabilities
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-325
