Repository hmcts/finrem-notification-service, pull requests merged in 2023-01, with the labels that each got.

#313 DFR-1715: List for hearing email template
  src/main/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-313

#315 Suppressing bad CVE
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-315

#316 Suppressing snakeyaml
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-316

#317 Bumping Tomcat
  build.gradle
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-317

#319 Suppressing Apache commons
  dependency-check-suppressions.xml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-319

#320 DFR-1758: update-chart-version
  charts/finrem-ns/Chart.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-320

#318 DFR-1638: High Court
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-318

#321 DFR-1783: Upgrade charts
  charts/finrem-ns/Chart.yaml
Labels: ns:financial-remedy, prd:finrem, rel:finrem-ns-pr-321
